apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dwnbx0unq-nodejs
  janus-idp.io/tekton: dwnbx0unq-nodejs
  backstage.io/kubernetes-id: dwnbx0unq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dwnbx0unq-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
