apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dwnbx0unq-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dwnbx0unq-nodejs 
  name: dwnbx0unq-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dwnbx0unq-nodejs 
